FROM node:20
WORKDIR /server
COPY ./client/dist ./dist
COPY ./server/config ./config
COPY ./server/controllers ./controllers
COPY ./server/middleware ./middleware
COPY ./server/models ./models
COPY ./server/routes ./routes
COPY ./server/templates ./templates
COPY ./server/package.json ./package.json
COPY ./server/server.js ./server.js
COPY ./server/tsconfig.json ./tsconfig.json
RUN npm install
EXPOSE 3001
CMD ["npm", "start"]
