FROM node:20
WORKDIR /server
COPY ./client/dist ./dist
COPY ./server/package.json ./package.json
COPY ./server/models ./models
COPY ./server/server.js ./server.js
RUN npm install
EXPOSE 3002
CMD ["npm", "start"]
