name: Build
run-name: Build and Lint
on:
  push:
    branches:
      - "main"
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Lint Client
        if: "!cancelled()"
        working-directory: ./client
        run: |
          ls
          npm install
          npm run lint
  build:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build Server
        if: "!cancelled()"
        working-directory: ./server
        run: |
          ls
          npm install
          npm run build
      - name: Build Client
        if: "!cancelled()"
        working-directory: ./client
        run: |
          ls
          npm install
          npm run build
