name: Build
run-name: Build and Lint
on: [push]
jobs:
  # lint:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: node:20
  #   steps:
  #     - name: Check out repository code
  #       uses: actions/checkout@v4
  #     - run: cd client
  #     - run: npm install --loglevel verbose
  #     - run: npm run lint
  # build:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: node:20
  #   steps:
  #     - name: Check out repository code
  #       uses: actions/checkout@v4
  #     - run: cd client
  #     - run: npm install --loglevel verbose
  #     - run: npm run build
  simple-test:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          ls
      - name: List files in the repository
        working-directory: ./server
        run: |
          ls
          npm install --loglevel verbose
          npm run lint
          npm run build
      - name: List files in the repository
        working-directory: ./client
        run: |
          ls
          npm install --loglevel verbose
          npm run lint
          npm run build
      - run: echo "🍏 This job's status is ${{ job.status }}."
